### ISSUE TITLE
stacks for uncaughtExceptions from basket calls

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-basket-proxy#18]
Followup to https://github.com/mozilla/fxa-basket-proxy/issues/16. Two uncaught today, with a restart. Basket was throwing back a bunch of failures, and I suppose in a race we had stacks like the below:

```
{"Timestamp":1456085723339000000,"Logger":"fxa-basket-proxy","Type":"routes.lookup-user.error","Severity":2,"Pid":15646,"EnvVersion":"2.0","Fields":{"er\
ror":"Error: ESOCKETTIMEDOUT","stack":"
    at ClientRequest.<anonymous> (/data/fxa-basket-proxy/node_modules/request/request.js:779:19)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.emit (events.js:92:17)
    at Socket.emitTimeout (http.js:1800:10)
    at Socket.g (events.js:180:16)
    at Socket.emit (events.js:117:20)
    at Socket._onTimeout (net.js:327:8)
    at _makeTimerTimeout (timers.js:438:11)
    at Timer.unrefTimeout [as ontimeout] (timers.js:502:5)"}}
{"Timestamp":1456085723341000000,"Logger":"fxa-basket-proxy","Type":"uncaughtException","Severity":0,"Pid":15646,"EnvVersion":"2.0","Fields":{"error":"E\
rror: Can't set headers after they are sent.","stack":"
    at ServerResponse.OutgoingMessage.setHeader (http.js:690:11)
    at ServerResponse.header (/data/fxa-basket-proxy/node_modules/express/lib/response.js:718:10)
    at ServerResponse.send (/data/fxa-basket-proxy/node_modules/express/lib/response.js:163:12)
    at ServerResponse.json (/data/fxa-basket-proxy/node_modules/express/lib/response.js:249:15)
    at Request.<anonymous> (/data/fxa-basket-proxy/lib/routes/lookup.js:22:23)
    at Request.emit (events.js:117:20)
    at ClientRequest.<anonymous> (/data/fxa-basket-proxy/node_modules/request/request.js:782:16)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.emit (events.js:92:17)
    at Socket.emitTimeout (http.js:1800:10)
    at Socket.g (events.js:180:16)
    at Socket.emit (events.js:117:20)
    at Socket._onTimeout (net.js:327:8)
    at _makeTimerTimeout (timers.js:438:11)
    at Timer.unrefTimeout [as ontimeout] (timers.js:502:5)"}}
```

**Comment by vladikoff** [comment]
@jrgm and @vladikoff to chat about this

**Comment by jrgm** [comment]
I'm wondering if this pattern is kosher - https://github.com/mozilla/fxa-basket-proxy/blob/master/lib/routes/lookup.js#L19-L24. It's start a pipe to the initial client, but if there is an error event it additionally tries to do `res.status`.

**Comment by rfk** [comment]
Sounds like a plausible explanation, if basket is erroring out .  I think it's still the right thing to *try* to send a error response to the client, but maybe we should catch it if it fails and just tear down the connection?

**Comment by jrgm** [comment]
I tried to build an example that would show this, but failed. I think it may be that the response has to have actually started, but stalls, and times out without completing. Which actually fits, since it's not all timeouts that fail, just some, hence a bit of a race.
